version: '3.1'
services:
  db:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: #.local1234
    ports:
      - 5432:5432
    volumes:
      - psql_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  psql_data:
    driver: local